### ISSUE TITLE
Consider supporting Mattermost servers with URL paths other than "/"

### ISSUE THREAD

**Issue by jtdaugherty** [ftilde/mattermost-session-cookie-firefox#1]
We just fixed support for this in `matterhorn` so it's on my mind: this script assumes the Mattermost server has no extra path segments in between the hostname and the API path, i.e.,
```
https://${webclient_host}/api/v4/users/me
```
but it is possible (and not terribly uncommon) for servers to have URLs like
```
https://${webclient_host}/OTHER_STUFF/api/v4/users/me
```
so I thought I'd mention this in case you want to support that in your script.

**Comment by ftilde** [comment]
Thank you for the heads-up! This should be possible with 84275f3725f2d4821d409243ca30b72b9e6c43a2 now, but (lacking access to such a server) I could not test this other than by debug printing URLs. If it turns out that the current support doesn't *really* work or is buggy somehow, please feel free to reopen this issue.

**Comment by jtdaugherty** [comment]
Thank you!
